# -*- coding: utf-8 -*-
"""FakeNewsDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp3fj6TJSCQYGLHU7qwNSDLVfMTjyXQ8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import pandas as pd
data = pd.read_csv('data.csv')

X_train, X_test, y_train, y_test = train_test_split(data['Body'].fillna(''), data['Label'], test_size=0.2, random_state=42)

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

tfidf_train = tfidf_vectorizer.fit_transform(X_train)

tfidf_test = tfidf_vectorizer.transform(X_test)

model = LogisticRegression(max_iter = 1000)
model.fit(tfidf_train, y_train)

sample_test = ['no war between russia and ukraine']
sample_tfidf = tfidf_vectorizer.transform(sample_test)
prediction = model.predict(sample_tfidf)
print(prediction)
